name: Concurrency 
on: [push]
concurrency: 
  # This workflow should be trigger for any branch only once 
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true # Existing will be canceled latest will be 
jobs: 
  hello: 
    runs-on: ubuntu-latest 
    steps: 
      - name: step1 
        run: sleep 20 